/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface SimpleStorageInterface extends utils.Interface {
  contractName: "SimpleStorage";
  functions: {
    "executeSetIfSignatureMatch(uint8,bytes32,bytes32,address,uint256,uint256)": FunctionFragment;
    "get()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "executeSetIfSignatureMatch",
    values: [
      BigNumberish,
      BytesLike,
      BytesLike,
      string,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "get", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "executeSetIfSignatureMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "get", data: BytesLike): Result;

  events: {};
}

export interface SimpleStorage extends BaseContract {
  contractName: "SimpleStorage";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SimpleStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    executeSetIfSignatureMatch(
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      sender: string,
      deadline: BigNumberish,
      x: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    get(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  executeSetIfSignatureMatch(
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    sender: string,
    deadline: BigNumberish,
    x: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  get(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    executeSetIfSignatureMatch(
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      sender: string,
      deadline: BigNumberish,
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    get(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    executeSetIfSignatureMatch(
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      sender: string,
      deadline: BigNumberish,
      x: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    get(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    executeSetIfSignatureMatch(
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      sender: string,
      deadline: BigNumberish,
      x: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    get(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
